package me.rpgz.treetools.ml

data class LeafLabel(
    val latinName: String,
    val chineseName: String
)

val id2label = mapOf(
    0 to LeafLabel("Acer palmatum", "鸡爪槭"),
    1 to LeafLabel("Aesculus chinensis", "七叶树"),
    2 to LeafLabel("Albizia julibrissin", "合欢"),
    3 to LeafLabel("Aucuba japonica var. variegata", "花叶青木"),
    4 to LeafLabel("Buxus sinica var. parvifolia", "雀舌黄杨"),
    5 to LeafLabel("Camptotheca acuminata", "喜树"),
    6 to LeafLabel("Cedrus deodara", "雪松"),
    7 to LeafLabel("Celtis sinensis", "朴树"),
    8 to LeafLabel("Cinnamomum camphora (Linn) Presl", "樟树"),
    9 to LeafLabel("Elaeocarpus decipiens", "杜英"),
    10 to LeafLabel("Euonymus japonicus", "大叶黄杨"),
    11 to LeafLabel("Euonymus japonicus Aureo_marginatus", "金边黄杨"),
    12 to LeafLabel("Flowering cherry", "樱花"),
    13 to LeafLabel("Ginkgo biloba", "银杏"),
    14 to LeafLabel("Juniperus chinensis Kaizuca", "龙柏"),
    15 to LeafLabel("Koelreuteria paniculata", "栾树"),
    16 to LeafLabel("Lagerstroemia indica", "紫薇"),
    17 to LeafLabel("Ligustrum lucidum", "女贞"),
    18 to LeafLabel("Liquidambar formosana", "枫香"),
    19 to LeafLabel("Liriodendron chinense", "鹅掌楸"),
    20 to LeafLabel("Llex cornuta", "枸骨"),
    21 to LeafLabel("Loropetalum chinense var. rubrum", "红花檵木"),
    22 to LeafLabel("Magnolia grandiflora L", "广玉兰"),
    23 to LeafLabel("Magnolia liliflora Desr", "紫玉兰"),
    24 to LeafLabel("Malushalliana", "海棠"),
    25 to LeafLabel("Metasequoia glyptostroboides", "水杉"),
    26 to LeafLabel("Michelia chapensis", "黄兰"),
    27 to LeafLabel("Michelia figo (Lour.) Spreng", "含笑"),
    28 to LeafLabel("Nandina domestica", "南天竹"),
    29 to LeafLabel("Nerium oleander L", "夹竹桃"),
    30 to LeafLabel("Osmanthus fragrans", "桂花"),
    31 to LeafLabel("Photinia serratifolia", "石楠"),
    32 to LeafLabel("Pinus massoniana Lamb", "马尾松"),
    33 to LeafLabel("Pinus parviflora", "五针松"),
    34 to LeafLabel("Pittosporum tobira", "海桐"),
    35 to LeafLabel("Platanus", "悬铃木"),
    36 to LeafLabel("Platycladus orientalis Beverlevensis", "侧柏"),
    37 to LeafLabel("Podocarpus macrophyllus", "罗汉松"),
    38 to LeafLabel("Populus L", "杨树"),
    39 to LeafLabel("Prunus cerasifera f. atropurpurea", "紫叶李"),
    40 to LeafLabel("Prunus persica", "桃树"),
    41 to LeafLabel("Rhododendron pulchrum", "毛鹃"),
    42 to LeafLabel("Sabina chinensis cv. Pyramidalis", "圆柏"),
    43 to LeafLabel("Salix babylonica", "垂柳"),
    44 to LeafLabel("Sapindus saponaria", "无患子"),
    45 to LeafLabel("Styphnolobium japonicum", "国槐"),
    46 to LeafLabel("Taxodium ascendens Brongn", "池杉"),
    47 to LeafLabel("Triadica sebifera", "乌桕"),
    48 to LeafLabel("Viburnum odoratissimum", "珊瑚树"),
    49 to LeafLabel("Zelkova serrata", "榉树")
)